FROM nodejs:20.12.2

# Set the working directory to /project
WORKDIR /app

ENV NODE_ENV=validation

# Copy package files in container currunt direcctory
COPY --chown=1001:1001 package.json package-lock.json ./


# Install all Angular dependacies
RUN npm ci

# Add application files in container 
COPY . .

# Set permision of .angular file in container
#VOLUME ["/project/.angular"]

# Open port to allow traffic in container
EXPOSE 8000

# Run start script using npm command
CMD ["node", "index.js"]
